name: Timberyard

on:
  push:
    branches: [ main, Development ]
  pull_request:
    branches: [ main, Development ]

jobs:
  linter:
    name:  Linter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 3.1.x
    - name: Install formater
      run: dotnet tool install --global dotnet-format
    - name: Run formater
      run: /home/runner/.dotnet/tools/dotnet-format --check --verbosity diagnostic

  build:
    needs: linter
    name:  Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Install formater
      run: dotnet tool install --global dotnet-format
    - name: Build
      run: dotnet build --no-restore

  unittests:      
    needs: build
    name:  Unit Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        dotnet-version: 3.1.x
    - name: Install formater
      run: dotnet tool install --global dotnet-format
    - name: Unit Tests-ETL
      run: dotnet test './ETLTests/ETLTests.csproj'
    - name: Unit Tests-Web Service
      run: dotnet test './Timberyard-UnitTests/TimberyardTests.csproj' --filter Category=Unit
  
  integrationtests:      
    needs: unittests
    name:  Integration Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        dotnet-version: 3.1.x
    - name: Install formater
      run: dotnet tool install --global dotnet-format
    - name: Initialize MS-SQL Server
      run: docker-compose --file ./testing-DB-docker-image/docker-compose.yaml up -d
    - name: Wait for server to init
      run: sleep 90s
    - name: Integration Tests-Web Service
      run: 
        export DatabaseSettings__ConnectionString="Initial Catalog=Timberyard;"
        export DatabaseSettings__DbServer="LOCALHOST\\SQLEXPRESS"
        export DatabaseSettings__DbPassword="timberyard_service"
        export DatabaseSettings__DbUsername="timberyard_service"
        export SMPTClientSettings__Host="localhost"
        export SMPTClientSettings__Port="25"
        export SMPTClientSettings__SenderAddress="Timberyard"
        dotnet test './Timberyard-UnitTests/TimberyardTests.csproj' --filter Category=Integration
    - name: Shutdown MS-SQL Server
      run:  docker-compose --file ./testing-DB-docker-image/docker-compose.yaml down