name: Timberyard

on:
  push:
    branches: [ main, Development ]
  pull_request:
    branches: [ main, Development ]

jobs:
  linter:
    name:  Linter
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Install formater
      run: dotnet tool install --global dotnet-format
    - name: Run formater
      run: dotnet-format --check --verbosity diagnostic

  build:
    needs: linter
    name:  Build
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Install formater
      run: dotnet tool install --global dotnet-format
    - name: Build
      run: dotnet build --no-restore

  unittests:      
    needs: build
    name:  Unit Tests
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        dotnet-version: 3.1.x
    - name: Install formater
      run: dotnet tool install --global dotnet-format
    - name: Unit Tests-ETL
      run: dotnet test '.\ETLTests\ETLTests.csproj'   