name: Timberyard

on:
  push:
    branches: [ main, Development ]
  pull_request:
    branches: [ main, Development ]

jobs:
  build:
    name:  Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore

  unittests:      
    needs: build
    name:  Unit Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        dotnet-version: 3.1.x
    - name: Unit Tests-ETL
      run: dotnet test './ETLTests/ETLTests.csproj' -l "console;verbosity=detailed"
    - name: Unit Tests-Web Service
      run: dotnet test './Timberyard-UnitTests/TimberyardTests.csproj' --filter Category=Unit -l "console;verbosity=detailed"
  
  integrationtests:      
    needs: unittests
    name:  Integration Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        dotnet-version: 3.1.x
    - name: Initialize MS-SQL Server
      run: docker-compose --file ./testing-DB-docker-image/docker-compose.yaml up -d
    - name: Wait for server to init
      run: sleep 120s
    - name: Integration Tests-Web Service
      run: |
        export DatabaseSettings__ConnectionString="Initial Catalog=Timberyard;"
        export DatabaseSettings__DbServer="LOCALHOST\\SQLEXPRESS,8080"
        export DatabaseSettings__DbPassword="sa"
        export DatabaseSettings__DbUsername="Password123!"
        export SMPTClientSettings__Host="localhost"
        export SMPTClientSettings__Port="25"
        export SMPTClientSettings__SenderAddress="Timberyard"
        dotnet test './Timberyard-UnitTests/TimberyardTests.csproj' --filter Category=Integration -l "console;verbosity=detailed"